lsst-dm/dm_dev_guide

development/lsstsw_tutorial.rst, index.rst, install.rst
See staged website at http://docs.lsst.codes/en/tickets-dm-4016/development/workflow.html
This guide is meant to be sufficient for a new hire to get started with the stack. It is intentionally light in details and special cases in many circumstances because I assume there will be additional in-depth guides written in the future that I can link to.
The guide focuses entirely on the lsstsw workflow since it was advocated as the best general workflow by the team.
https://community.lsst.org/t/what-development-workflow-should-be-advocated-w-poll/297?u=jsick
A separate guide should be written around using the shared stack on the NCSA cluster.
For DM-4016
=> DM-4016 lsstsw dev workflow tutorial

development/code_of_conduct.rst, index.rst
http://docs.lsst.codes/en/tickets-dm-4658/development/code_of_conduct.html
Original page source:
https://confluence.lsstcorp.org/display/LDMDG/Team+Culture+and+Conduct+Standards
(by K-T Lim; Aug 19, 2015)
For DM-4658.
=> DM-4658: Port Team Culture and Conduct from Confluence

development/decision_process.rst, index.rst
http://docs.lsst.codes/en/tickets-dm-4657/development/decision_process.html
=> DM-4657: Port RFC/RFD/Decision Making Doc

coding/python_testing.rst
This is a first attempt to codify the decision from last week's JTM.
=> First draft at unicode for testing

processes/decision_process.rst
An adoption plan is created during the consensus phase, but the tickets are created during the adoption phase.
=> DM-5876: Clarify when tickets are created for RFC adoption

coding/using_astropy.rst, conf.py, index.rst
This is going to be a fluid section of the dev guide as we develop Astropy interoperability and integration.
=> Add Astropy usage recommendation

processes/workflow.rst
Notifications to community.lsst.org for significant features/bug fixes; release notes for anything affecting users.
=> Suggest notifications after ticket closure.

processes/code_of_conduct.rst
We went from 3-in-a-box to a more hierarchical organization.
=> Remove Project Scientist

coding/python_testing.rst, coding/unit_test_snippets/unittest_runner_example.py
Create pull request for comments.
=> DM-6823: Update test boilerplate and update testing intro

coding/python_testing.rst
Draft at https://developer.lsst.io/v/DM-7281/coding/python_testing.html
=> DM-7281: Update python testing dev guide to reflect updated TestCase methods

coding/logging.rst, coding/logging_snippets/tracing.py, index.rst
Preview: https://developer.lsst.io/v/DM-7530/coding/logging.html
=> DM-7530: Add the science pipeline logging guide

processes/workflow.rst, tools/git_setup.rst
**Preview**
- https://developer.lsst.io/v/DM-7919/processes/workflow.html#git-setup
- https://developer.lsst.io/v/DM-7919/tools/git_setup.html
****
See https://community.lsst.org/t/the-dangers-of-git-on-lsst-dev/1216?u=jsick for background.
=> DM-7919: Add git config requirement for 'simple' pushes

coding/unit_test_policy.rst
https://developer.lsst.io/v/DM-8038/coding/unit_test_policy.html
=> Specify shared-library variant of Boost.Test

coding/python_testing.rst
=> DM-7476: Clarify log configuration in unit tests

index.rst, services/datasets.rst, services/verification.rst
=> DM-8534: Add documents for Common Dataset Organization and Policy

processes/decision_process.rst
This is intended to replace Frossie's tickets/DM-5888 branch.
=> Revise management including new TCT

coding/python_style_guide.rst
This is the implementation of RFC-205.
=> Add note banning "if false" to python dev guide tickets/DM-7532

getting-started/onboarding.rst
https://developer.lsst.io/v/DM-8441/getting-started/onboarding.html
=> DM-8441: Update account on-boarding checklist

processes/decision_process.rst
First draft of changes to the decision making process to move RFDs from JIRA to community. Should not be merged until the corresponding infrastructure in community has been implemented.
=> DM-9082: change RFD location

docs/rst_section_sample.rst, docs/rst_styleguide.rst
Fixes/clarifications to the ReStructuredText Style Guide
=> Fix reST section example

services/verification.rst
This adds a couple of bits that answer questions I had about the verification cluster when I started using it recently.
=> clarify some verification cluster details

coding/cpp_style_guide.rst
https://developer.lsst.io/v/DM-9007/coding/cpp_style_guide.html
=> DM-9007: Clarify C++ construction syntax

coding/logging.rst
https://developer.lsst.io/v/DM-9419/coding/logging.html
=> DM-9419: Link to Doxygen on logging.

coding/pybind11_style_guide.rst
=> DM-9869: Add guidelines for useful stringification to DM Pybind11 Style Guide

getting-started/onboarding.rst
T/CAMs are not a subset of the DMLT.
=> Specifically mention T/CAMs for calendar access

services/lsst-dev.rst, tools/git_lfs.rst
- https://developer.lsst.io/v/DM-11225/services/lsst-dev.html#configure-git-lfs (Using Git LFS on lsst-dev)
- https://developer.lsst.io/v/DM-11225/tools/git_lfs.html#basic-git-lfs-configuration (adds a config section on running `git lfs install`, which is useful for those who got git-lfs from EUPS rather than installing it themselves).
=> DM-11225: Improve Git LFS configuration docs for lsst-dev

docs/cpp_docs.rst
This pull request corrects a number of mistakes in previous statements about how Doxygen works and adds some gotchas I found in the last few months of working on the Stack.
=> DM-10220: Miscellaneous corrections to C++ Doxygen guidelines

build-ci/lsstsw.rst
Added section on how to update EUPS version.
Added it at the very end of the lsstsw page of the tutorial.
=> DM-9719: Document EUPS update process for lsstsw stacks

services/data_protection.rst
Copy via Paul Domagala at NCSA.
=> Update scratch purge policy

docs/technotes.rst
Highlights:
- Creating a technote with Slack
- Creating a LaTeX technote
- Using bibtex in reStructuredText technotes
Draft: https://developer.lsst.io/v/DM-12311/docs/technotes.html
=> DM-12311: Update technote user docs

coding/cpp_style_guide.rst, coding/using_boost.rst, teams/drp.rst
=> DM-10342: Switch to C++14

coding/cpp_style_guide.rst
Implements RFC-209.  Text has been modified slightly from original RFC proposal to include destructors and incorporate discussion on documentation.
=> DM-7994: Add recommendations on compiler-generated members.

coding/cpp_style_guide.rst, coding/profiling.rst, coding/pybind11_style_guide.rst, coding/python_testing.rst, coding/python_wrappers_for_cpp_with_pybind11.rst, coding/using_astropy.rst, coding/using_cpp_templates.rst, conf.py, docs/change-controlled-docs.rst, docs/jsdoc.rst, docs/package_docs.rst, docs/py_docs.rst, docs/rst_section_sample.rst, docs/rst_styleguide.rst, getting-started/onboarding.rst, processes/publication-policy.rst, processes/workflow.rst, services/data_protection.rst, services/lsst-db.rst, services/ncsa_bulk_transfer.rst, services/verification.rst, tools/emacs.rst, tools/git_lfs.rst, tools/git_setup.rst, tools/vim.rst
Fixes some warnings and trailing whitespace issues. No change in content.
=> DM-5383 precursor cleanups

services/lsst-dev.rst
=> Drop old shared stacks.

services/data_protection.rst
=> Make snapshot availability more explicit.

legal/copyright-overview.rst, legal/copyright.py, stack/license-and-copyright.rst
Also fix some incorrect text in the copyright overview.
=> Add copyright generation script.

work/flow.rst
=> Allow merged branches to be removed.

team/onboarding.rst
Per request from Ranpal, 2018-09-07.
=> Request mail to dm-staff on offboarding.

.travis.yml, pybind11/how-to.rst, services/lsst-dev.rst, services/storage.rst
This fixes some syntax issues that have appeared in the storage page and in the Pybind11 page.
It also makes the build more stringent against syntax errors and deployment failures so we don't have these issues in the future.
=> DM-16031: Fix syntax errors and instate build feedback

services/lsst-dev.rst
I was too hasty in my editing on the last commit.
=> DM-16129: Properly describe retired stack.

python/style.rst
This matches the style already used in the guide and in our code.
=> DM-16296: Add W504 to style guide

project-docs/technotes.rst
Until the `sqrbot project create` command is back, these instructions tell folks how to create the repository themselves.
https://developer.lsst.io/v/u-jonathansick-technote-repo-assignment/project-docs/technotes.html#create-a-technote
=> Add explicit steps for creating a technote repo

communications/rfc.rst
I have added some text in the Exceptions and appeals section, trying to capture what was discussed today in the DMCCB#6 and in DMCCB#3.
I did not mention that the workflow needs to be updated.
=> Added Board Recommended status details

communications/rfc.rst
This sentence comes out of an action item from DMCCB minutes.
=> Mention that we might ask for triggered issues to be created prior to approval

python/testing.rst
Reopens #121 with the text in a different place.
=> DM-7450: Add note about shebang in test files

services/lsst-dev.rst
And move stack_20190330 to archive.
=> DM-21527: Switch to devtoolset-8 shared stack.

python/testing.rst
These make it easy to iterate over parameter combinations.
=> DM-22199: Add decorators for iterating over tests

editors/sublime.rst, python/style.rst, python/testing.rst
Change W504 to W503.
cc/ @r-owen
=> DM-23162: Implement RFC-650 and state that we want to break before binary operators

cpp/style.rst
Hello. I came across this document and thought maybe this variable should be renamed.
=> Replace variable with a more appropriate name

stack/deprecating-interfaces.rst
=> Add version= to Python/pybind11 deprecations.

services/software.rst
Triggered by https://jira.lsstcorp.org/browse/IHS-4152
=> Add system python 2.7 & 3.6 documenation

services/lsst-login.rst
See https://jira.lsstcorp.org/browse/IHS-4176
=> Bring attention to kerberos ticket expiration

cpp/style.rst, python/style.rst
=> DM-21147: Permit snake_case variables and functions more broadly.

communications/community-support.rst, communications/index.rst, index.rst, team/onboarding.rst
Primarily, a reference to DMTN-155.
=> DM-26765: Update developer guide to reference the interim model for community support

editors/vscode.rst, stack/eups-tutorial.rst
=> Fix dead links.

stack/moving-to-github-actions.rst
Note that admin rights are needed, and optimize the command-line procedure.
=> Improve Travis-to-GHA documentation.

services/batch.rst
Added a short section describing extra steps required to use Batch Production Service (BPS) with NCSA HTCondor cluster.
=> DM-28801: Add documentation to LSST developer guide for using BPS on NCSA resources

work/flow.rst
Since I'm apparently the first one to follow this procedure, I turned it into a more explicit checklist.
=> Make checklist for community contributions

python/profiling.rst
Rendered output is here: https://developer.lsst.io/v/DM-34882/python/profiling.html
=> DM-34882: modernize profiling docs

.github/workflows/ci.yaml, .github/workflows/cron-ci.yaml
- Update action versions to resolve a breakage in setup-python 2
- Update Python version to 3.10
=> DM-35270: Refresh GitHub Actions actions

git/git-lfs.rst
This problem was discovered by Marcella Di Criscienzo in https://lsstc.slack.com/archives/CAS7Y9ADS/p1676545637893539
=> Document workaround for git lfs on small memory.

stack/building-pipelines-lsst-io-locally.rst
I removed what I think are all the outdated instructions, but please let me know if I need to keep some of the removed text in, change anything else. I wanted to get this moved as soon as possible since others have also run into the issue of their stack breaking when following the current instructions and it can be frustrating. If you'd prefer it left alone for now I can close the pull request.
=> DM-38873: Remove outdated instructions

conf.py
I meant to do this as part of #613 but forgot to include this commit before merging!
=> Update COPYRIGHT year

build-ci/jenkins.rst, coding/unit-test-policy.rst, jenkins/getting-started.rst, stack/building-pipelines-lsst-io-locally.rst, stack/building-pipelines-lsst-io-with-documenteer-job.rst, stack/documentation-system-overview.rst, stack/jenkins-stack-os-matrix.rst, stack/platforms.rst
Also update the macOS versions.
=> Replace ci.lsst.codes with SLAC URL.

stack/jenkins-stack-os-matrix.rst
Built page: https://developer.lsst.io/v/DM-43582/stack/jenkins-stack-os-matrix.html#running-a-stack-os-matrix-job
=> DM-43582: Add notes about ci_ap

team/onboarding.rst
Also add a bit of text about off-boarding and GitHub.
=> Update onboarding for USDF.

team/drp.rst
Reflecting recent updates to the repositories available on-disk at Princeton.
=> Update the Princeton compute cluster information

usdf/kubernetes.rst
In particular, add the `module load` commands needed to activate kubectl and vault.
Also add a current list of vclusters.
=> Add information on Kubernetes at USDF.

usdf/onboarding.rst
This updates the onboarding documentation with additional information that is required by DOE for foreign nationals.
=> Update onboarding.rst w/ onboarding requirements

usdf/onboarding.rst
=> add coact step to onboarding

usdf/onboarding.rst
This just adds some temporary text about current access control training until it receives more SLAC automation.
=> Update onboarding.rst w/ access control training
