development/git_lfs.rst
index.rst

See http://docs.lsst.codes/en/tickets-dm-4469/development/git_lfs.html
This document centralizes Git LFS user documentation that has otherwise
been stored in the READMEs of individual repos.
This is meant to be a top-level document in developer docs since our
implementation of Git LFS is unique and it is a developer-facing tool.
Splits out words there were previously in #4, but really belong on their own
since LFS needs user documentation and shouldn't be confused with
the collaboration process documentation being written in #4.
For DM-4469.

DM-4469: Create Git LFS guide

---

tools/git_lfs.rst
tools/snippets/git_lfs_git-credentials.txt
tools/snippets/git_lfs_gitconfig.txt

* Reasoning: git-lfs 1.1.0+ doesn't accept empty username and passwords for the git-lfs server or secondary storage system. So the documentation needs to be updated.
* Add documentation to configure the git credential store to use empty username and passwords for the secondary storage systems and the git-lfs server.
modified:   tools/git_lfs.rst

[DM-4888] Update documentation to support git-lfs 1.1.0+.

---

coding/cpp_style_guide.rst
coding/intro.rst
coding/python_style_guide.rst
coding/using_cpp_templates.rst
coding/using_cpp_templates_snippets/Foo.cc
coding/using_cpp_templates_snippets/Foo.h
coding/using_cpp_templates_snippets/README.md
coding/using_cpp_templates_snippets/Sconstruct
coding/using_cpp_templates_snippets/main.cc
conf.py
index.rst

http://docs.lsst.codes/en/tickets-dm-4656/
See 'Coding Guides' section, which has a port of the coding standards (C++ and Python) originally published in the Confluence DM Developer Guide.
No content is changed. The purpose of this review is ensure this is an adequate representation of the style guides in reStructuredText/Sphinx.

DM-4656 Port Code Style Guidelines to new docs

---

conf.py

This is needed to prevent duplicate label warnings.
Fixes bug introduced in DM-4793.

DM-5690 Fix exclude path for doc snippets

---

tools/git_setup.rst

This commit solves the issue where a reader might go to git_setup.rst to guidance on how to *use* Git for DM work rather than the official workflow document (workflow.rst). These need to be separate pages because the latter is a requirements document, and the former is intended to be simply helpful.
- Rename "Git Setup and Best Practices" to "Git Configuration Best Practices" to make scope clearer.
- Expand the See also section to make it easier for someone who landed on the Git Configuration Best Practices document to make their way into the appropriate part of the Workflow document.

DM-5826: Clarify division of Git setup and workflow docs

---

.travis.yml
build-ci/eups_tutorial.rst
build-ci/lsstsw.rst
build-ci/third_party.rst
coding/python_style_guide.rst
coding/unit_test_policy.rst
docs/rst_styleguide.rst
requirements.txt

This PR adds a Travis configuration to build the developer guide and publish to LSST the Docs (at developer.lsst.io).
Minor changes to existing reference syntax was required because of the move to nit-picky builds (see https://ltd-mason.lsst.io/travis.html#travis-setup-for-a-pure-sphinx-repository) to help ensure that intended code references do in fact resolve in successful builds. References to code objects in the `lsst` namespace can be re-added in the future.

Publish with LSST the Docs

---

coding/unit_test_policy.rst
conf.py
requirements.txt

`documenteer.sphinxext` gives us mock versions of Python references roles so that LSST code can be marked-up semantically in a way that'll be easy to transition once the Pipelines docs are published with sphinx.
These roles are the standard code reference roles, just preprended with `l`, as in 'lsst.'
E.g.
```
:lclass:`~lsst.utils.tests.MemoryTestCase`
```

DM-6326: Add documenteer package for LSST Sphinx extensions

---

.gitignore
Makefile
coding/python_testing.rst
coding/unit_test_policy.rst
coding/unit_test_snippets/testExecutables.py
coding/unit_test_snippets/unittest_baseclass.py
coding/unit_test_snippets/unittest_basic_example.py
coding/unit_test_snippets/unittest_runner_example.py
conf.py

Modifications to the developer guide to add instructions on how LSST DM code should do python testing.

DM-5973: Add python testing instructions

---

processes/workflow.rst

I'm unsure how Enhancement was originally named as a ticket type; perhaps the ticket types were re-organized?
https://developer.lsst.io/v/DM-6639/processes/workflow.html

DM-6639: Change Enhancement ticket to Improvement

---

tools/git_lfs.rst
tools/snippets/git_lfs_gitconfig.txt

The purpose of this change is to repeat the result from a git config --global lfs.batch false to remind folks that this configuration is needed in case the earlier documentation lines were skipped. See
https://community.lsst.org/t/issues-using-git-lfs-for-cloning-test-data-repositories/880/16?u=jsick
https://developer.lsst.io/v/u-jonathansick-git-lfs-doc/tools/git_lfs.html

Add lfs batch config lines

---

coding/python_style_guide.rst
docs/py_docs.rst
docs/rst_styleguide.rst
processes/workflow.rst

This PR updates the Python Style Guide in response to two accepted RFCs:
- [RFC 162: LSST Python Style Guide delta to PEP 8](http://ls.st/rfc-162)
- [RFC 214: Use numpydoc docstrings](http://ls.st/rfc-214)
Both the 'Python Style Guide' and 'Documenting Python APIs' pages are being updated in the same ticket since they effectively form the Python Style Guide as a whole—the numpydoc material is simply too detailed to include with the rest of the style guide.
Live preview of these revised pages:
- https://developer.lsst.io/v/DM-5456/coding/python_style_guide.html
- https://developer.lsst.io/v/DM-5456/docs/py_docs.html

DM-5456: Python Style Guide as a diff of PEP 8 and accept Numpydoc

---

coding/python_style_guide.rst

* Python 3 now mandatory
* Python 2.7 optional
* Update Idioms section to remove mention of idioms that don't work on Python 3.

DM-6317: Update Python style guide for Python 3

---

docs/py_docs.rst

I saw the "interable" typo in one of the docstring examples. I assume I don't actually need to fill out an RFC for changes on this level...

Fix spelling: interable -> iterable

---

coding/cpp_style_guide.rst
conf.py

- The original page on confluence was deprecated by
services/lsst-dev.rst
- Reformatted as a nice seealso block for clarity.

DM-7568: Fix link in C++ Style Guide to using devtoolset-3

---

coding/python_style_guide.rst
docs/py_docs.rst

- https://developer.lsst.io/v/DM-7526/coding/python_style_guide.html
- https://developer.lsst.io/v/DM-7526/docs/py_docs.html

DM-7526: Copy edits to the Python Style Guide & Numpydoc Guide

---

coding/python_style_guide.rst
docs/py_docs.rst

- Consolidates all docstring layout advice into the 'Documenting Python APIs' page. This is a change-controlled extension of the Python Style Guide.
- Distinguish between preceding/following blank space guidelines for PEP 257 consistency. Docstrings for classes are **followed** by a blank line.

DM-7539: Change Python docstring before/after blank space guidelines for consistency with PEP 257 (RFC-218)

---

build-ci/lsstsw.rst

Having a bash and a csh example present should be sufficient, given
that `deploy` provides interactive instructions as well.

Added setup script example for csh shells.

---

services/lsst-dev.rst

The description is the shortest I can find that wouldn't confuse the vast majority of users not affected by [DM-7651](https://jira.lsstcorp.org/browse/DM-7651).
The compiled text can be found at https://developer.lsst.io/v/DM-7651/services/lsst-dev.html#generate-a-key-pair.

DM-7651: Clarify in dm_dev_guide that SSH keys must be in one-line format

---

getting-started/onboarding.rst

- T/CAMs now onboard team members in community categories using the group page, not the admin interface.
- Reformat from definition list to sections
https://developer.lsst.io/v/DM-7674/getting-started/onboarding.html

DM-7674: Update Community category onboarding

---

tools/git_lfs.rst

Original wording made it sound like the brew upgrade should be done right after a brew install.

Delineate brew install from upgrade in time

---

index.rst

DMTN-027 should (probably) get incorporated into the DM Dev Guide. This is a quick fix.

Add link to DMTN-027

---

getting-started/onboarding.rst
processes/workflow.rst

The content of this update is already common knowledge in DM, but never explicitly written. This PR also explicitly bars developers from using personal repositories for LSST funded work.
Draft: https://developer.lsst.io/v/DM-8144/processes/workflow.html#github-orgs

DM-8144: Document GitHub orgs: lsst/lsst-dm/lsst-sqre

---

coding/python_testing.rst

As the current default log configuration is already good,
the hard-coded log configuration in unit test initialization
is removed; DM-7150 is reverted. Update the doc about that.
This reverts commit 32ae0fb386e84aa274708985ae133fae5d246482
and 491caf0f95a6f2f6e15a348be917895a285eb3d8.

DM-8605: Remove log configuration in unit test initialization

---

index.rst
processes/presenting-at-conferences.rst
processes/publication-policy.rst

This adds two new pages describing DM's policies and procedures surrounding conference presentations and publications:
- https://developer.lsst.io/v/DM-8586/processes/presenting-at-conferences.html
- includes information on how to upload presentations to Zenodo.
- https://developer.lsst.io/v/DM-8586/processes/publication-policy.html
- Links to Publication Board documentation

DM-8586: Policies for presentations and publications

---

conf.py
requirements.txt

The third-party [sphinx_rtd_theme](https://github.com/snide/sphinx_rtd_theme) needs to be pinned to an unreleased development version in order to get a search fix described in https://github.com/snide/sphinx_rtd_theme/pull/346.
It works: file:///Users/jsick/lsst/dm_dev_guide/_build/html/search.html?q=git&check_keywords=yes&area=default

DM-9256: Fix search with Sphinx 1.5

---

tools/git_lfs.rst
tools/snippets/git_lfs_git-credentials_legacy.txt
tools/snippets/git_lfs_gitconfig_legacy.txt

Update git-lfs documentation to reflect the new API and configuration changes.
* The batch option was required to force the git-lfs client to use
the legacy API. Now that the batch API (DM-5737) is implemented and
the legacy API is deprecated and will soon to be removed,
references should be removed.
* Remove unnecessary configuration.
* Add note about legacy git-lfs client configuration differences.
* Remove recommendation of creating a repository `.gitconfig` file.
* Leave in reference of repository `.gitconfig`.
* Add recommended client verison.
modified:   tools/git_lfs.rst
modified:   tools/snippets/git_lfs_git-credentials.txt
new file:   tools/snippets/git_lfs_git-credentials_legacy.txt
modified:   tools/snippets/git_lfs_gitconfig.txt
new file: …

[DM-9261] Update git-lfs documentation to reflect the new API and configuration changes.

---

docs/cpp_docs.rst

This is a rewrite of the C++ documentation guide to have similar format and content to the [Python documentation guide](https://developer.lsst.io/docs/py_docs.html). All changes discussed in [RFC-225](https://jira.lsstcorp.org/browse/RFC-225) have been included. However, any inconsistencies between the new text and the [Confluence documentation](https://confluence.lsstcorp.org/display/LDMDG/Documentation+Standards) have not been resolved; they will be addressed as part of [DM-7892](https://jira.lsstcorp.org/browse/DM-7892).
A compiled version of the new style guide is available at https://developer.lsst.io/v/DM-7891/docs/cpp_docs.html. The actual diff is quite messy, with `git diff` apparently using blank lines as reference points.

DM-7891: Add detailed C++ documentation guidelines

---

.travis.yml

The docs.scipy.org outage has been breaking docs builds because the unresolved intersphinx links are warnings that `-W` is turning into errors. This commit temporarily removes that flag while docs.scipy.org is generally unavailable.
See
https://community.lsst.org/t/how-docs-scipy-org-and-intersphinx-affect-your-doc-builds/1717?u=jsick
from a long-term mitigation strategy.

DM-9815: Remove -W sphinx-build flag b/c of docs.scipy.org

---

docs/jsdoc.rst
index.rst

File added:
dm_dev_guide/docs/jsdoc.rst
File modifiled:
dm_dev_guide/index.rst
This branch is a modified one based on the reviews in the branch tickets/DM-7554.

DM-7554: Publish JSDoc how-to document to  https://developer.lsst.io.

---

coding/python_style_guide.rst

This PR adds recommended flake8 linter path exclusion configuration to the Python Style Guide.
Draft: https://developer.lsst.io/v/DM-9919/coding/python_style_guide.html#flake8-configuration-files
- `bin` is autogenerated, so it shouldn't be linted (whereas `bin.src/` *should* be linted).
- `doc/` includes `conf.py` for Sphinx which may not be readily lintable because of its global namespace usage for configuration.
- `__init__.py` modules shouldn't be linted since they're often just configuring a namespace, requiring 'unused' imports.
- `version.py` is autogenerated and shouldn't be linted.
- `tests/.tests` is autogenerated.
I've implemented this commit as only showing the final recommended configuration. I don't think its necessary to justify each path exclusion, but we could iterate on …

DM-9919: Add flake8 path exclusion configuration

---

coding/cpp_style_guide.rst
coding/python_style_guide.rst

The ticket provides a brief rationale for centralizing technical debt information in Jira. The examples are taken from RFC-307 comments.
Affected pages:
* https://developer.lsst.io/v/DM-9966/coding/python_style_guide.html
* https://developer.lsst.io/v/DM-9966/coding/cpp_style_guide.html

DM-9966: Recommend that TODO comments link to Jira

---

docs/cpp_docs.rst

This ticket makes the [Confluence documentation page](https://confluence.lsstcorp.org/display/LDMDG/Documentation+Standards) fully obsolete. Cross-references from the C++ documentation style guide to Confluence have been removed. Exact changes copied over are listed on [Jira](https://jira.lsstcorp.org/browse/DM-7892).
This ticket also fixes a few bugs that have been found in the new style guide after DM-7891 was closed.
All changes are to https://developer.lsst.io/v/DM-7892/docs/cpp_docs.html.

DM-7892: Transfer relevant C++ doc guidelines from Confluence to Developer Guide

---

coding/python_style_guide.rst

@jonathansick can you please take a quick look at this before I send for review from K-T? I've tried to put in the RFC-97 decision but my initial problem is that we are sometimes stating a PEP-8 exception that is not actually an exception so I've moved those up and left the exceptions lower down. I wonder if the N80x exceptions need their own sections now that they only apply to Science Pipelines and it may be better to have one item along the lines of "Science Pipeline shall use camelCase".
The variable naming one with `l`, `O` and the like is in PEP-8 so I've added a note saying that rather than letting there be an implication that this is against PEP-8.

DM-7579: Update naming rules based on RFC-97

---

coding/python_style_guide.rst

**Draft:** https://developer.lsst.io/v/DM-9509/coding/python_style_guide.html#autopep8-may-be-used-to-fix-pep-8-compliance
Older versions treated whitespace above and below docstrings improperly. See https://jira.lsstcorp.org/browse/DM-9509

Clarify that autopep8 >= 1.2 is required

---

services/lsst-dev.rst

After the pybind11 port, it appears that we cannot mix devtoolset-3 and base stacks.  Add this caveat to the document.

Add caveats for devtoolset-3

---

getting-started/onboarding.rst

From Libby. Only DMLT need full access to the calendars. For regular DM members there's still calendars available on the project website.

Change calendar access to DMLT only

---

coding/python_style_guide.rst

https://developer.lsst.io/v/u-jonathansick-python-style-guide-typo/coding/python_style_guide.html#keyword-assignment-operators-should-be-surrounded-by-a-space-when-statements-appear-on-multiple-lines

Typo fix in multiline assignment rule (Python Style Guide)

---

tools/git_lfs.rst

- Slim down the installation docs to rely on documentation from Git LFS/GitHub itself.
- Change the configuration documentation model so that *everyone* runs through the configuration steps. A second section covers the `git push` authentication pattern.
@jmatt What permissions are needed by the GitHub personal token? I can include that at the same time.
https://developer.lsst.io/v/DM-11002/tools/git_lfs.html

DM-11002: Simplify Git LFS documentation

---

requirements.txt

Documenteer 0.2.0 changes how dependencies for different projects are managed. We can do the work to sort out required dependencies and upgrade later.

DM-11334: Pin documenteer < 0.2.0

---

processes/workflow.rst

The developer guide mentions HipChat in a couple of places. Replaced
them by Slack.

Remove HipChat mentions from dev guide

---

coding/debug.rst

The `-d` option doesn't exist, and `--debug` does not do what was described for `-d`.

Fix incorrect command line task doc.

---

services/datasets.rst

Allow RFC-approved tags for reruns in /datasets per RFC-362 (1)

DM-11291: Update Common Dataset Organization and Policy per RFC-362

---

coding/python_wrappers_for_cpp_with_pybind11.rst

See [RFC-376](https://jira.lsstcorp.org/browse/RFC-376) for templates re-org. and  Since the templates repo is now generalized it is necessary to link to the correct example itself.
See also lsst/templates#4
Note that we're thinking about moving the pybind11 example out of [lsst/templates](https://github.com/lsst/templates), so this link might again change.

DM-11513: Update Pybind11 example for templates re-org

---

build-ci/eups_tutorial.rst

sw.lsstcorp.org was deprecated and eups.lsst.codes/stack/src is the new root for source builds (this tutorial doesn't need to get into the binary distribution root yet).

DM-11908: Update eups package root to eups.lsst.codes/[..] for EUPS tutorial

---

processes/workflow.rst

I had originally thought the section on "master" was better, but I've come around to @jdswinbank 's suggestion of putting it in the "merge" section.

Added note on reverting build-breaking changes.

---

build-ci/platforms.rst
index.rst

It turns out that we don't write down anywhere what operating systems we are really supporting. Here are some words for people to argue over.

First attempt at writing down supported platforms

---

services/verification.rst

/project is mentioned in https://developer.lsst.io/services/data_protection.html but not in this document.

Document /project.

---

build-ci/jenkins-stack-os-matrix.rst

I needed to create an extra reST link target for
``stack-os-matrix dashboard`` and ``stack-os-matrix``.

Fix link to stack-os-matrix dashboard

---

services/lsst-dev.rst

At least two people have hit this subtlety in the last couple of weeks.

lsst-dev: note that xpra requires py2

---

docs/py_docs.rst

This PR includes many improvements to the Numpydoc documenation for developers. See the draft online at https://developer.lsst.io/v/DM-12951/docs/py_docs.html
- Clarified formatting of Returns section (https://jira.lsstcorp.org/browse/DM-12926)
- Clarified formatting of Parameters section (https://jira.lsstcorp.org/browse/DM-12936)
- More accurate recommentations for attribute documentation based on real-world experience.
- Better and more accurate examples.
- Lots of copy edits.

DM-12951: Improve Numpydoc documentation

---

teams/drp.rst

"module load" is better than "scl enable".

drp: update devtoolset-6 activation

---

.gitignore
README.md
coding/python_style_guide.rst
conf.py
docs/cpp_docs.rst
docs/package_docs.rst
docs/snippets/license_preamble.txt

Follows the discussion in RFC-45. I've also tried to factor out the license text that is present in each source in a single location referenced from C++ and Python guides.

DM-5383: Update copyright instructions

---

docs/py_docs.rst
docs/snippets/numpydocExample.py

https://developer.lsst.io/v/DM-13525/docs/py_docs.html
- Clarify that class attributes and parameters are documented separately.
- Example of returning an `lsst.pipe.base.Struct`.
- Full example module (based on http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy)
- Easier to use table of contents

DM-13525: Improve numpydoc examples

---

build-ci/jenkins-stack-os-matrix.rst
build-ci/jenkins.rst
communications/slack-github-username.rst
index.rst

Documentation for the new Jenkins job notifications feature in Slack:
- [Slack job notifications](https://developer.lsst.io/v/DM-13582/build-ci/jenkins.html#slack-job-notifications)
- [Getting stack-os-matrix notifications in Slack](https://developer.lsst.io/v/DM-13582/build-ci/jenkins-stack-os-matrix.html#getting-stack-os-matrix-notifications-in-slack)
- [Configuring your GitHub username in your Slack profile](https://developer.lsst.io/v/DM-13582/communications/slack-github-username.html)

DM-13582: Document Jenkins slack notifications

---

index.rst
it/index.rst
it/itsc.rst

Describes the ITSC, using content provided by the ITSC.
This PR must be merged *after* #209.
Draft: https://developer.lsst.io/v/DM-13856/it/itsc.html

DM-13856: Add ITSC page

---

pybind11/how-to.rst

Update the "Python wrappers for C++ with pybind11" tutorial (https://developer.lsst.io/v/DM-14005/pybind11/how-to.html) to point the relocated example package (we've moved it out of lsst/templates since the example is not formally a template).
See also:
- https://github.com/lsst-dm/pybind11_example/pull/1
- https://github.com/lsst/templates/pull/10

DM-14005: Update links to pybind11_example repository

---

services/datasets.rst

I added a paragraph about including a `README.txt` in any new addition to datasets.  I'd like @jonathansick to have a look at it for content and syntax.

DM-13508: Add a note about a README.txt in `datasets`

---

cpp/style.rst
index.rst
services/storage.rst

Fixes build warnings for pages in `services` and a broken link in the C++ style guide.

DM-14203: Address build warnings

---

Makefile
conf.py
services/monitoring_applications.rst

- Update copyright to 2018
- Fixup syntax errors
- Update intersphinx URLs to use https
- Turn warnings into breaking errors during the build to prevent syntax errors from making it to master in the future

Maintenance updates

---

python/numpydoc.rst
python/style.rst

This ticket modifies the style guide to no longer mention 110-character lines. The changed pages are https://developer.lsst.io/v/DM-8980/coding/python_style_guide.html and https://developer.lsst.io/v/DM-8980/docs/rst_styleguide.html.

DM-8980: Revise Python Style Guide for RFC-107 (79 character line lengths)

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst
stack/documentation-system-overview.rst

Adjust link to documenteer.lsst.io now that DM-14852 has been merged.

DM-14852: Patch documenteer URLs

---

editors/sublime.rst

the settings did not work because of this missing comma

mising comma

---

stack/packaging-third-party-eups-dependencies.rst

@TallJimbo suggested text reflecting the fact that sconsUtils doesn't pick up changes to third-party headers.

Add text about announcing new/upgraded packages.

---

project-docs/technotes.rst

This change will be reverted once the technote creation service (`sqrbot project create`) is available/reliable again.

Recommend manual technote creation for now

---

git/git-lfs.rst

So testdata_decam is 1.6 GB so takes a while. Testdata_subaru is 190 MB and that is also a git-lfs repo so maybe better for a test

Smaller example repo

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst

Now that that work is merged, developers can work against the `master` branch of https://github.com/lsst/pipelines_lsst_io

DM-15802: Remove references to DM-11216's branch

---

requirements.txt

This also pins to Sphinx < 1.8.0, where we are seeing inoperative search.

Update to documenteer 0.3.0

---

legal/copyright.py

This PR fixes a bug where the `git log` output was being read as raw bytes rather than text, breaking parsing.

DM-15858: copyright.py breaks on Python 3.6+

---

legal/copyright.py

Handle some non-institutional email addresses, and include CNRS/IN2P3 as
an institution, which in turn requires a special exception.

Update copyright file generator script.

---

stack/layout-of-doc-directory.rst
stack/module-homepage-topic-type.rst
stack/package-homepage-topic-type.rst

This is some text unresolved from DM-15024 when we dropped package docs if there was a Python/C++ module present.
There is a new URL for the example file as well (post DM-15024 fix).

DM-15973: Fix so package docs don't have modules section

---

python/style.rst

This is intended as a stop-gap until RFC-34 is implemented.

Describe permitted styles for Python imports.

---

project-docs/technotes.rst

In newer versions of sphinxcontrib-bibtex and its dependencies, the `latex+latin` encoding is no longer needed, and in fact has become an error:
```
unknown encoding: "latex+latin"
```

DM-14360: Remove encoding field from bibliography directive

---

restructuredtext/examples/figure.rst
restructuredtext/examples/image.rst

This PR modifies the image linking example as discussed on the corresponding [Jira issue](https://jira.lsstcorp.org/browse/DM-16443). The new version of the page can be found at https://developer.lsst.io/v/DM-16443/restructuredtext/style.html.

DM-16443: RST Guide Example Broken

---

stack/logging.rst

There were no examples of how to configure subtask logging on the commandline or in a config.
Here's the built version: https://developer.lsst.io/v/u-parejkoj-add-log-config/stack/logging.html#logging-within-the-task-framework

Add log configuration examples

---

cpp/api-docs.rst

This PR requests that packages be documented using the new Sphinx system, and adds a comment explaining the existing policy behind `@file` (some questions about it came up during the December UW/Princeton numpydoc hack week).
Note that the C++ wording is slightly different from the [Python equivalent](https://developer.lsst.io/python/numpydoc.html#py-docstring-module-structure), but I'd argue that that's necessary because of differences in the two languages (in C++, "file" and "module" are essentially independent concepts).

DM-16814: Replace Packages section in C++ Documentation Guide

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst
stack/module-homepage-topic-type.rst

The pyvenv strategy for isolating documenteer from the Stack's conda environment seems to be error prone based on user feedback. It's easy to use the wrong Python and end up with a Python environment that doesn't make sense. With this commit we're removing mention of the virtual environment and instead recommending that the documenteer package is installed directly into the stack's conda environment. This emulates the likely endgame anyhow, where documenteer is packaged with conda and distributed as part of the conda environment.
- https://developer.lsst.io/v/DM-16935/stack/building-single-package-docs.html
- https://developer.lsst.io/v/DM-16935/stack/building-pipelines-lsst-io-locally.html

Remove pyvenv instructions from documenteer installation steps

---

cpp/api-docs.rst
python/examples/numpydocExample.py
python/numpydoc.rst

This update replaces much of the inherited wording from the numpydoc spec to help us be more explicit about how the extended summary and notes sections of docstrings should be used. The extended summary exists to support the summary sentence. The Notes section is the heart of the docstring's conceptual documentation.
The C++ guidelines are also updated for parity.
Pending [RFC-558](
https://jira.lsstcorp.org/browse/RFC-558).
Drafts:
- [Documenting Python APIs with docstrings and Numpydoc](https://developer.lsst.io/v/DM-16826/python/numpydoc.html)
- [Documenting C++ code](
https://developer.lsst.io/v/DM-16826/cpp/api-docs.html)

DM-16826: Clarify usage of "Extended summary" and "Notes" sections

---

python/examples/numpydocExample.py
python/numpydoc.rst

This PR improves guidelines for documenting parameters in Numpydoc:
- For Struct and dict parameters with known keys, we now recommend documenting those specific attributes/keys as definition list items, rather than in a plain list. This is more semantically useful. The examples also show multi-paragraph descriptions. [See draft documentation](
https://developer.lsst.io/v/DM-16827/python/numpydoc.html#struct-types).
- For container types (lists and dicts) we now recommend using PEP 484-like syntax [See draft documentation](
https://developer.lsst.io/v/DM-16827/python/numpydoc.html#dictionary-types).
- New documentation for how to handle `*args` and `**kwargs`. [See draft documentation](
https://developer.lsst.io/v/DM-16827/python/numpydoc.html#additional-positional-and-keyword-arguments) …

DM-16827: Definition lists for Structs and *args/**kwargs guidelines

---

conf.py
index.rst
user-docs/index.rst
user-docs/lsst-specific-content-style-guide.rst

This PR implements the idea of a user documentation content style guide that's based on Google's, with tweaks for LSST use cases. [RFC-555](https://jira.lsstcorp.org/browse/RFC-555)
There are a lot of additional areas this can go. I'd like to compile a bibliography of technical communication books, blogs, and talks, for instance. But this scope is enough for the style guide project to start being useful.
Preview of the entrypoint to the guide: https://developer.lsst.io/v/DM-11462/index.html#part-user-doc-style-guide

DM-11462: Start the user documentation style guide

---

project-docs/publication-policy.rst

The old version was a 404.
Debated whether going through the ls.st shortener or directly linking to
Docushare was the correct approach; decided on the former, because although it
introduces a single point of failure, it also means there's a single place to
update if Docushare moves again.

Fix URL for LPM-162.

---

project-docs/technotes.rst

With DM-18606 the lsst-sqre/lsst-technote-bootstrap migrated to lsst/templates and is now templatekit-based.
Note that this is an interim solution until we announce the SQuaRE bot method for creating technotes.

DM-18606: Update instructions for creating an rst-formatted technote

---

pybind11/how-to.rst
pybind11/style.rst

This PR removes the rules on return value policies from the pybind11 style guide, after adding a descriptive section to the pybind11 tutorial.

DM-19812: Remove rule on return value policy from pybind11 style guide

---

conf.py
requirements.txt

- Update documenteer to 0.5.x to resolve the docutils issue described in https://github.com/lsst-sqre/documenteer/pull/65
- Temporarily update the intersphinx link for pytest as described in https://github.com/pytest-dev/pytest/issues/5641 (the process of getting pytest.org back up is taking longer than anticipated).
- Update the sphinx_rtd_theme to 0.4.x to get their latest design updates and fixes
https://developer.lsst.io/v/DM-20736/index.html

DM-20736: Update to documenteer 0.5.x, pytest intersphinx

---

conf.py
cpp/clang-format.rst
cpp/style.rst
cpp/templates.rst
pybind11/how-to.rst
pybind11/style.rst
python/style.rst
python/testing.rst
stack/deprecating-interfaces.rst
stack/logging.rst
stack/lsstsw.rst
stack/package-homepage-topic-type.rst
stack/packaging-third-party-eups-dependencies.rst
stack/task-topic-type.rst
work/project-planning.rst

This PR sets the default role (text in single backticks) to be the `:obj:` role. This provides a flexible way to generate links to any Sphinx API reference, and any supported language, just by wrapping the API name in single backticks. This replaces the need for spelling out roles like `:py:meth:` or even `:meth:`.
Specifically, this PR:
1. Configured the default role
2. Fixed earlier usage of the default role that was accidental
3. Converted content, where applicable, to use the default role.
The PR also switches the intersphinx link for pipelines.lsst.io to use the weekly edition, and removes a duplicate entry.
Preview: https://developer.lsst.io/v/DM-20448/

DM-20448: Adopt the default role for code links

---

_templates/layout.html
conf.py
requirements.txt

This merges the layout.html of the sphinx-rtd-theme at 0.4.3
(https://raw.githubusercontent.com/readthedocs/sphinx_rtd_theme/0.4.3/sphinx_rtd_theme/layout.htm) with the custom div to add the version switcher to the sidebar.
This also takes advantage of the new `canonical_url` theme setting to create a `<link rel="canonical"...>` header tag to ensure that search engines always point to the main edition of the docs.

DM-20762: Update layout template to match sphinx-rtd-theme 0.4.3

---

project-docs/change-controlled-docs.rst

This allows pull requests of release branches to be merged to master.
This approach has been approved by DMCCB.
@jonathansick for some reason my enumerated lists are being forced into bullets and I'm not entirely sure why.

DM-17861: Update change-controlled doc instructions to allow release branch merge

---

conf.py
legal/copyright-overview.rst
project-docs/technotes.rst
stack/argparse-script-topic-type.rst
stack/config-topic-type.rst
stack/license-and-copyright.rst
stack/script-topic-type.rst
stack/task-topic-type.rst

Wherever the docs talk about creating a file from a template, or creating a technote, we now provide instructions on how to use @sqrbot-jr on Slack to create that file or project. This is probably the easiest, fastest, and least error-prone way we now have of creating new files and projects.
The docs feature deep links to the `@sqrbot-jr` direct message in the reader's Slack client or web browser (see https://api.slack.com/docs/deep-linking#app_or_bot).
One page that could benefit from this treatment is "Adding a New Package to the Build", but updating that page to mention `@sqrbot-jr create project` would likely require additional edits to that page that are best left to a different PR.

DM-21117: Feature @sqrbot-jr for creating files and technotes from templates

---

team/onboarding.rst

URL 'dm-tea-time' updated from erroneous 'dm-tea-team'

DM-21723: Fix URL to dm-tea-time

---

editors/vim.rst

Added extra Vim config information to ensure that filetype configurations are always recognised (https://developer.lsst.io/editors/vim.html).

DM-21736: Add setup information enabling Vim file type recognition

---

services/datasets.rst

While creating the reference catalog readme file, I realized we could use more guidance about how to manage the contents of this file.

DM-20267: Add required README.txt to /datasets/refcats/htm

---

legal/copyright-overview.rst
legal/copyright.py

They would like ", Inc. (AURA)" added at the end.

DM-21738: Change AURA copyright text based on feedback from Gemini lawyers

---

README.md

This primarily reflects the availability of the `/v` endpoint for finding documentation drafts.

Update contribution process in README

---

conf.py
stack/module-homepage-topic-type.rst

This update mentions pipeline tasks, what to do if there are pipeline tasks but not regular tasks, and also links to the documenteer docs.
Draft: https://developer.lsst.io/v/DM-22520/stack/module-homepage-topic-type.html#task-reference-section
Note that the boilerplate code will automatically update when  https://github.com/lsst/templates/pull/60 is merged.

DM-22520: Mention pipeline tasks in module documentation guidelines

---

restructuredtext/style.rst

Some minor things I noticed while reading the RST guide.
- Add missing paren to the `:abbr:` example
- Recommend anonymous links when using inline URLs
- Be explicit about the input and output example for Python interactive sessions

Minor fixes to the RST guide

---

index.rst

The guide for building and testing stack packages lives in pipelines.lsst.io, but it's useful to have that link from the DM Stack section of the Developer Guide too.

Link to package development guide

---

services/lsst-dev.rst

SIMS-2621 is resolved in practice, although Jira hasn't yet been updated.

Mark lsst_sims available in latest shared stack.

---

work/flow.rst

This PR implements the wording changes from [RFC-670](https://jira.lsstcorp.org/browse/RFC-670), clarifying that post-review squashing is recommended, but not required so long as DM quality standards are not compromised.

DM-23649: Relax dev guide wording on post-review squashing

---

git/git-lfs.rst

2FA access tokens also need the `public_repo` scope.

PATs need an additional scope.

---

services/lsst-dev.rst

add rh-git218
remove git19 (no longer maintained)
remove rh-git29 (no longer maintained)
We are only removing these from documentation for now (not necessarily removing them from dev servers).

Update git SCLs available

---

services/lsst-dev.rst

Remove references to devtoolset 3 & 4. No LSST software should be currently built using these, plus these versions are no longer being patched for security issues. This change removes them from documentation only -- removing them from the systems is a later task.

Remove outdated devtoolset references

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst

This is needed to suppress warnings about being unable to create diagrams.

Mention how to install graphviz.

---

python/testing.rst

The special asserts mentioned there had been out of date since DM-10096.

DM-25061: Update unit testing page of developer guide

---

project-docs/change-controlled-docs.rst
project-docs/technotes.rst

In DM-25233 and revised in DM-25659 we've added templates and the ability to create any type of lsstdoc/LaTeX document via the `sqrbot-jr project create` command.
This PR adds documentation to that effect: https://developer.lsst.io/v/DM-25659/project-docs/change-controlled-docs.html#ccd-create
Also, since technote templates have migrated to GitHub Actions, a PR is no longer needed for the document to appear on the web. I've updated the technote creation guide:
https://developer.lsst.io/v/DM-25659/project-docs/technotes.html#create-a-technote

DM-25659: Document change-controlled doc creation via sqrbot-jr

---

services/datasets.rst

remove reference to /datasets/public_html which has been relocated to /lsstdata/user/staff/web_data

remove reference to /datasets/public_html

---

services/lsst-login.rst

I’m not sure we want people doing ssh lsst-login.ncsa.illinois.edu (to the CNAME that points to all 3 nodes). That seems like it will create havoc with trusting hostkeys and with kerberos host keys. I haven’t done a lot of testing with it… I just worry that it might cause unpredictable user issues.

Remove reference to lsst-login.ncsa.illinois.edu

---

restructuredtext/style.rst

Add some options for Emacs display of one-sentence-per-line that
may make this style easier to read for some people.

Add Emacs settings for one-sentence-per-line

---

python/style.rst

These examples were not updated when RFC-650 was implemented.

Make examples agree with binary operator rule.

---

python/style.rst

...but they should be minimal, especially if they don't have a .py
suffix.
This implements RFC-698.

DM-25710: Clarify that executable scripts do not need .py suffixes.

---

team/drp.rst

As Yusra AlSayyad has taken over the role of John Swinbank, the DRP page is updated to show this change.

Replace John with Yusra

---

python/numpydoc.rst
python/style.rst

Allow the closing triple-quote for a one-line docstring in Python
code to be on either the same line as the opening quote or on the
following line.  This permits compliance with PEP 257 and the
formatting enforced by black.  See RFC-762 for discussion.

[DM-29292] Relax formatting rule for one-line docstrings

---

git/git-lfs.rst

Update the list of `git lfs` repositories.
Indicate that `git lfs` comes from conda in most installations.
Indicate that `git lfs install` only needs to be run once.
Remove old version information.

Update for modern `git lfs`.

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst

This PR updates the Pipelines documentation build instructions given that documenteer is now included in the Science Pipeline's conda environment:
- https://developer.lsst.io/v/DM-29889/stack/building-single-package-docs.html
- https://developer.lsst.io/v/DM-29889/stack/building-pipelines-lsst-io-locally.html
In https://github.com/lsst/templates/pull/118 we're updating the template, and that will automatically be reflected in an updated section on the doc/conf.py file in the "Layout of the doc/ directory page" https://developer.lsst.io/stack/layout-of-doc-directory.html#the-doc-conf-py-file (the code sample pulls data from the templates repo).

DM-29889: Update documentation for building Science Pipelines documentation with Documenteer in conda

---

work/flow.rst

As described in [RFC-784](https://jira.lsstcorp.org/browse/RFC-784), a GitHub PR's title shouldn't need to match the title of a Jira ticket. The Jira ticket captures a unit of work whereas the PR describes a specific code change.

DM-30381: Change guidelines so a PR title does not need to match the Jira issue title

---

pybind11/style.rst

I noticed that the pybind11 section about python properties was still a TBD, but RFC-279 was implemented years ago. I think all we need here is a link to the python section, no?

Add link to from pybind11 to python property section

---

work/flow.rst

The link was pointing to a non-existent page.

Fix user branch link

---

python/testing.rst

I keep referring back to my community post[1] on this topic, and figured it should be in the dev guide.
I wonder if we need to rework the paragraph just above my new one, since it refers to stdout? It also says "rare standalone usages": I don't know that that's exactly "rare"?
1: https://community.lsst.org/t/recent-changes-to-science-pipelines-logging/5732/4?u=parejkoj

Add note about pytest log messages

---

stack/adding-a-new-package.rst

The "how to make a new package" instructions were buried in a hard to find paragraph in amongst the RFC stuff. It makes more sense to have it be the first thing a user sees.
As-built version:
https://developer.lsst.io/v/u-parejkoj-create-a-package/stack/adding-a-new-package.html

Make "create a package" more prominent

---

git/setup.rst

The rendered version: https://developer.lsst.io/v/DM-35388/git/setup.html#tune-your-shell-for-git

DM-35388: Fix dev guide links in "tune your shell for git"

---

stack/jenkins-stack-os-matrix.rst

This PR updates the description of the `stack-os-matrix` job to reflect current practice, and adds some notes about gotchas that I've run into myself.
The built documentation can be found at https://developer.lsst.io/v/DM-36409/stack/jenkins-stack-os-matrix.html.

DM-36409: Update stack-os-matrix docs to reflect current system

---

stack/adding-a-new-package.rst
stack/building-pipelines-lsst-io-locally.rst

analysis_tools was RFCed and added to the build without having docs linked from pipelines.lsst.io, without a descriptive readme, and without any real built docs to speak of. Having docs is a critical part of any new package, so we need this as part of our "how to add a package" documentation.
I also cleaned up some bad links and other text and added more sections.

Add requirements for built docs to new package guide

---

stack/deprecating-interfaces.rst

This PR adds a missing space between "Observatory"  and "Science".

DM-36385: Fix typo in example deprecation warning.

---

stack/layout-of-doc-directory.rst

- The template already sets the package name, so no need to reference the project_name variable or version (which is no longer settable).
- Clarify that the file shouldn't be modified.

DM-37425: Update documentation for doc/conf.py

---

requirements.txt

Pin Sphinx<6; Sphinx 6 dropped packaging jquery and that's hampering the on-site search functionality. I think that sphinx_rtd_theme show take over including jquery, but I'll have to verify.

Pin Sphinx<6

---

.gitignore
conf.py
restructuredtext/style.rst

Part of the reStructuredText style guide, this shows how to use external with the ref and doc roles for intersphinx

Document the external role for linking

---

index.rst
user-docs/index.rst
user-docs/topic-based-documentation.rst

This page is based on talks I've given to DM on organizing documentation around topics and using topics types to create consistent documentation structures.
See draft: https://developer.lsst.io/v/DM-35567/user-docs/topic-based-documentation.html
Question for review — this page has initially involved into two themes: exploring topic-based technical writing, and then designing content for users (i.e. headers, short paragraphs, lists, code samples). I'm wondering whether this page works well as it is, or if it should be split up?

DM-35567: Add guide on topic-based writing for users

---

team/onboarding.rst

A link in the onboarding guide to the `lsst-dm` organization pointed to `lsst` instead.

Fix bad link to lsst-dm GitHub org.

---

stack/building-pipelines-lsst-io-locally.rst
stack/building-single-package-docs.rst

The dev guide did not say anything about `rubin-env-developer`, which is where the `package-docs` command now lives. I tried to reword this page to reflect this; not sure if the `mamba` command should be pulled out into a separate bullet?

Add notes on dev env to single package docs build

---

python/astropy.rst

as requested by the DM-CCB on RFC-921.

DM-39199: Add a note about FITS libraries from Python

---

python/numpydoc.rst

This PR adds a couple of notes to the documentation clarifying how to do multi-line PRs and how to resolve relative type names.
Compiled version at https://developer.lsst.io/v/DM-38916/python/numpydoc.html.

DM-38916: Document edge-case behavior of Python type descriptions

---

work/flow.rst

This patch makes searching for TODO comments with current ticket number an explicit step in the development workflow.

Add searching for TODO recommended

---

stack/jenkins-stack-os-matrix.rst

The default build target now includes lsst_sitcom. Built docs are available at https://developer.lsst.io/v/u-kfindeisen-lsst-sitcom/stack/jenkins-stack-os-matrix.html.

Update stack-os-matrix documentation with new default.

---

team/drp.rst

Owing to potential confusion, LATISS data will be stored at Princeton in /repo/main. This is in-keeping with the long-term plans for LATISS data at the USDF.

Remove reference to embargo repo at Princeton

---

restructuredtext/examples/def-list.rst
restructuredtext/style.rst

Our own guides should not have the old acronym

Update LSST acronym in RST guide

---

stack/conda.rst
stack/lsstsw.rst

Replace reference to bin/setup.sh with bin/envconfig.
Adds documentation on how to change rubin-env version with a different one.

DM-45482: Replace reference to setup.sh with envconfig and add how to change rubin-env

---

usdf/onboarding.rst

Added instruction for POC name being different on Site Access Form.

POC Instruction Update to Avoid Name Issue

---

communications/slack-culture.rst

This edit focuses on channel naming guidelines to make content consistent with the content and intent of the obs-ops guide. It then rationalises some of the remaining text for uniformity.

Focus on channel naming guidelines

---

communications/slack-culture.rst

Reflect the new name for the help-slack channel that was changed as per K-T's suggestion.

Update the Slack usage help channel name

---

python/astropy.rst
usdf/onboarding.rst

Also clarify that S3DF registration should be done before accessing S3DF or RSP accounts.

add on-boarding step to fill out staff access form

---

python/style.rst

Worth adding a note to the dev guide on this after what I learned on [DM-50559](https://rubinobs.atlassian.net/browse/DM-50559).
[DM-50559]: https://rubinobs.atlassian.net/browse/DM-50559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add warning on abstract building subclasses

---

usdf/storage.rst

Adding info here although this is to be replaced by df-ops.lsst.io.

Update Butler repo information.
